{
	"name": "ContextSensitive",
	"version": "1.0.23",
	"icon": "fas fa-brain",
	"category": "alice",
	"author": "ProjectAlice",
	"maintainers": [
		"Psycho",
		"maxbachmann"
	],
	"desc": "ContextSensitive is the official context sensitive skill. It handles intents like 'Delete this', 'Change that', 'Please repeat",
	"aliceMinVersion": "1.0.0-b1",
	"systemRequirements": [],
	"pipRequirements": [],
	"conditions": {
		"lang": [
			"en",
			"fr",
			"de",
			"it"
		]
	}
}
